"""Self-contained HTML report renderer.

Produces a single static HTML document with inline CSS (no external assets) so
reports can be emailed or archived. All dynamic content is HTML-escaped.
"""

from __future__ import annotations

from html import escape

from .. import __version__

_SEVERITY_COLORS = {
    "critical": "#7c1d1d",
    "high": "#b45309",
    "medium": "#a16207",
    "low": "#2563eb",
    "info": "#4b5563",
}


def _badge(severity: str) -> str:
    color = _SEVERITY_COLORS.get(severity, "#4b5563")
    return (
        f'<span class="badge" style="background:{color}">'
        f"{escape(severity.upper())}</span>"
    )


def render_html(result) -> str:
    """Render a :class:`ScanResult` as a standalone HTML report."""
    counts = result.severity_counts()
    summary_cells = "".join(
        f'<div class="stat"><div class="stat-n">{counts[s]}</div>'
        f'<div class="stat-l">{_badge(s)}</div></div>'
        for s in ("critical", "high", "medium", "low", "info")
    )

    rows = []
    for f in result.sorted_findings():
        refs = "".join(
            f'<li><a href="{escape(r)}">{escape(r)}</a></li>' for r in f.references
        )
        refs_block = f"<ul class='refs'>{refs}</ul>" if refs else ""
        url = f'<div class="mono">{escape(f.url)}</div>' if f.url else ""
        evidence = (
            f'<div class="evidence">Evidence: {escape(f.evidence)}</div>'
            if f.evidence
            else ""
        )
        cve = f' &middot; <span class="mono">{escape(f.cve)}</span>' if f.cve else ""
        rows.append(
            f"""
        <article class="finding">
          <header>{_badge(f.severity.value)}
            <h3>{escape(f.title)}</h3>
            <span class="score">CVSS {f.score:.1f}{cve}</span>
          </header>
          <p>{escape(f.description)}</p>
          {url}
          {evidence}
          <p class="remediation"><strong>Remediation:</strong> {escape(f.remediation)}</p>
          {refs_block}
        </article>"""
        )

    findings_html = "\n".join(rows) or "<p>No findings. </p>"
    highest = result.highest_severity.value if result.highest_severity else "none"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>WP-Sentinel Report — {escape(result.target.base_url)}</title>
<style>
  body {{ font-family: system-ui, sans-serif; margin: 0; background: #f8fafc; color: #1e293b; }}
  .wrap {{ max-width: 920px; margin: 0 auto; padding: 2rem 1.25rem 4rem; }}
  h1 {{ margin: 0 0 .25rem; font-size: 1.5rem; }}
  .meta {{ color: #64748b; font-size: .9rem; margin-bottom: 1.5rem; }}
  .mono {{ font-family: ui-monospace, monospace; font-size: .85rem; color: #475569;
           word-break: break-all; }}
  .summary {{ display: flex; gap: .75rem; flex-wrap: wrap; margin-bottom: 1.5rem; }}
  .stat {{ background: #fff; border: 1px solid #e2e8f0; border-radius: 10px;
           padding: .75rem 1rem; min-width: 90px; text-align: center; }}
  .stat-n {{ font-size: 1.6rem; font-weight: 700; }}
  .badge {{ color: #fff; border-radius: 999px; padding: .1rem .55rem;
            font-size: .72rem; font-weight: 700; letter-spacing: .03em; }}
  .finding {{ background: #fff; border: 1px solid #e2e8f0; border-left-width: 5px;
              border-radius: 10px; padding: 1rem 1.25rem; margin-bottom: 1rem; }}
  .finding header {{ display: flex; align-items: center; gap: .6rem; flex-wrap: wrap; }}
  .finding h3 {{ margin: 0; font-size: 1.05rem; flex: 1; }}
  .score {{ color: #64748b; font-size: .8rem; }}
  .evidence {{ font-size: .85rem; color: #475569; margin: .35rem 0; }}
  .remediation {{ background: #f1f5f9; border-radius: 8px; padding: .6rem .8rem;
                  font-size: .92rem; }}
  .refs {{ font-size: .82rem; }}
  footer {{ margin-top: 2rem; color: #94a3b8; font-size: .8rem; text-align: center; }}
</style>
</head>
<body>
<div class="wrap">
  <h1>WP-Sentinel Security Report</h1>
  <div class="meta">
    Target: <span class="mono">{escape(result.target.base_url)}</span><br>
    Profile: {escape(result.profile_name)} &middot;
    Duration: {result.duration_seconds:.2f}s &middot;
    Highest severity: {_badge(highest) if highest != "none" else "none"} &middot;
    Checks run: {len(result.checks_run)}
  </div>
  <div class="summary">{summary_cells}</div>
  {findings_html}
  <footer>
    Generated by WP-Sentinel v{escape(__version__)} — non-destructive, authorized-use only.
  </footer>
</div>
</body>
</html>
"""
