"""Markdown report renderer.

Produces a human-readable report suitable for pasting into issues, wikis, or PR
descriptions. Includes an executive summary, a hardening score, and per-finding
technical detail with OWASP/CWE mapping, evidence, and remediation.
"""

from __future__ import annotations

from .. import __version__

_EMOJI = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🔵",
    "info": "⚪",
}


def render_markdown(result) -> str:
    counts = result.severity_counts()
    score = result.hardening_score()
    grade = result.grade()
    highest = result.highest_severity.value if result.highest_severity else "none"

    lines: list[str] = []
    lines.append("# WP-Sentinel Security Report")
    lines.append("")
    lines.append(f"**Target:** `{result.target.base_url}`  ")
    lines.append(f"**Profile:** {result.profile_name}  ")
    lines.append(f"**Duration:** {result.duration_seconds:.2f}s  ")
    lines.append(f"**Checks run:** {len(result.checks_run)}")
    lines.append("")

    # Executive summary
    lines.append("## Executive summary")
    lines.append("")
    lines.append(f"- **Hardening score:** {score}/100 (grade **{grade}**)")
    lines.append(f"- **Highest severity:** {highest}")
    lines.append(f"- **Total findings:** {len(result.findings)}")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for sev in ("critical", "high", "medium", "low", "info"):
        lines.append(f"| {_EMOJI[sev]} {sev.capitalize()} | {counts[sev]} |")
    lines.append("")

    if result.errors:
        lines.append("> ⚠️ Some checks reported errors: "
                     + "; ".join(result.errors))
        lines.append("")

    # Technical detail
    lines.append("## Findings")
    lines.append("")
    if not result.findings:
        lines.append("_No findings. The scanned surface looks clean._")
    for i, f in enumerate(result.sorted_findings(), start=1):
        lines.append(f"### {i}. {_EMOJI[f.severity.value]} {f.title}")
        lines.append("")
        meta = [f"**Severity:** {f.severity.value}", f"**CVSS:** {f.score:.1f}"]
        if f.owasp:
            meta.append(f"**OWASP:** {f.owasp}")
        if f.cwe:
            meta.append(f"**CWE:** {f.cwe}")
        if f.cve:
            meta.append(f"**CVE:** {f.cve}")
        lines.append(" · ".join(meta))
        lines.append("")
        lines.append(f.description)
        lines.append("")
        if f.url:
            lines.append(f"- **Affected URL:** `{f.url}`")
        if f.evidence:
            lines.append(f"- **Evidence:** `{f.evidence}`")
        lines.append(f"- **Remediation:** {f.remediation}")
        if f.references:
            refs = ", ".join(f"[ref]({r})" for r in f.references)
            lines.append(f"- **References:** {refs}")
        lines.append("")

    lines.append("---")
    lines.append(f"_Generated by WP-Sentinel v{__version__} — "
                 "non-destructive, authorized-use only._")
    return "\n".join(lines) + "\n"
